bmake[1]: "cond-op-and.mk" line 37: Malformed conditional (0 || (${DEF} && ${UNDEF}))
bmake[1]: "cond-op-and.mk" line 42: Malformed conditional (0 || (${UNDEF} && ${UNDEF}))
bmake[1]: "cond-op-and.mk" line 45: Malformed conditional (0 || (!${UNDEF} && ${UNDEF}))
bmake[1]: "cond-op-and.mk" line 75: Malformed conditional (0 &&& 0)
bmake[1]: Fatal errors encountered -- cannot continue
bmake[1]: stopped in unit-tests
1
