bmake.exe[1]: "cond-op-parentheses.mk" line 22: Comparison with '>' requires both operands '3' and '(2' to be numeric
bmake.exe[1]: "cond-op-parentheses.mk" line 25: Malformed conditional ((3) > 2)
bmake.exe[1]: "cond-op-parentheses.mk" line 44: Malformed conditional (()
bmake.exe[1]: "cond-op-parentheses.mk" line 58: Malformed conditional ())
bmake.exe[1]: Fatal errors encountered -- cannot continue
bmake.exe[1]: stopped in unit-tests
1
