bmake[1]: "cond-func.mk" line 37: Missing closing parenthesis for defined()
bmake[1]: "cond-func.mk" line 53: Missing closing parenthesis for defined()
bmake[1]: "cond-func.mk" line 57: Missing closing parenthesis for defined()
bmake[1]: "cond-func.mk" line 98: The empty variable is never defined.
bmake[1]: "cond-func.mk" line 108: A plain function name is parsed as defined(...).
bmake[1]: "cond-func.mk" line 116: A plain function name is parsed as defined(...).
bmake[1]: "cond-func.mk" line 127: Symbols may start with a function name.
bmake[1]: "cond-func.mk" line 133: Symbols may start with a function name.
bmake[1]: "cond-func.mk" line 139: Missing closing parenthesis for defined()
bmake[1]: Fatal errors encountered -- cannot continue
bmake[1]: stopped in unit-tests
1
