bmake.exe[1]: "deptgt.mk" line 11: warning: Extra target '.PHONY' ignored
bmake.exe[1]: "deptgt.mk" line 30: Unassociated shell command ": command3		# parse error, since targets == NULL"
Parsing line 36: ${:U}: empty-source
ParseDependency(: empty-source)
Parsing line 37: 	: command for empty targets list
Parsing line 38: : empty-source
ParseDependency(: empty-source)
Parsing line 39: 	: command for empty targets list
Parsing line 40: .MAKEFLAGS: -d0
ParseDependency(.MAKEFLAGS: -d0)
bmake.exe[1]: "deptgt.mk" line 49: Unknown modifier "Z"
bmake.exe[1]: "deptgt.mk" line 52: warning: Extra target 'ordinary' ignored
bmake.exe[1]: "deptgt.mk" line 55: warning: Extra target (ordinary) ignored
bmake.exe[1]: "deptgt.mk" line 58: warning: Special and mundane targets don't mix. Mundane ones ignored
bmake.exe[1]: Fatal errors encountered -- cannot continue
bmake.exe[1]: stopped in unit-tests
1
