direct compat
exit 1
*** Error code 1 (continuing)

Stop.
bmake[2]: stopped in unit-tests
exited 1

direct jobs
exit 1
*** [direct] Error code 1

bmake[2]: stopped in unit-tests
exited 1

indirect compat
exit 1
*** Error code 1 (continuing)
`indirect' not remade because of errors.

Stop.
bmake[2]: stopped in unit-tests
exited 1

indirect jobs
exit 1
*** [direct] Error code 1

bmake[2]: stopped in unit-tests
exited 1

0
