bmake[1]: "opt-debug-lint.mk" line 21: Variable "X" is undefined
bmake[1]: "opt-debug-lint.mk" line 21: Malformed conditional ($X)
bmake[1]: "opt-debug-lint.mk" line 45: Variable "UNDEF" is undefined
bmake[1]: "opt-debug-lint.mk" line 45: Malformed conditional (${UNDEF})
bmake[1]: "opt-debug-lint.mk" line 67: Missing delimiter ':' after modifier "L"
bmake[1]: "opt-debug-lint.mk" line 67: Missing delimiter ':' after modifier "P"
bmake[1]: "opt-debug-lint.mk" line 76: Unknown modifier "${"
bmake[1]: Fatal errors encountered -- cannot continue
bmake[1]: stopped in unit-tests
1
