echo 3   spaces& exit 1
3   spaces

*** Failed target:  fail-spaces
*** Failed command: echo 3 spaces& exit 1
*** Error code 1 (continuing)
echo   indented& exit 1
  indented

*** Failed target:  fail-escaped-space
*** Failed command: echo indented& exit 1
*** Error code 1 (continuing)
echo line1&echo:line2& exit 1
line1
line2

*** Failed target:  fail-newline
*** Failed command: echo line1${.newline:Q}line2& exit 1
*** Error code 1 (continuing)
echo line1 line2& exit 1
line1 line2

*** Failed target:  fail-multiline
*** Failed command: echo line1 line2& exit 1
*** Error code 1 (continuing)
echo	'word1'							 'word2'& exit 1
'word1'							 'word2'

*** Failed target:  fail-multiline-intention
*** Failed command: echo 'word1' 'word2'& exit 1
*** Error code 1 (continuing)
`all' not remade because of errors.

Stop.
bmake.exe[1]: stopped in unit-tests
1
