ECHO is on.
:D expanded when var set
true
TRUE
:U expanded when var undef
true
TRUE
:D skipped if var undef
ECHO is on.
:U skipped when var set
is set
:? only lhs when value true
true
TRUE
:? only rhs when value false
false
FALSE
do not evaluate or expand :? if discarding
is set
year=2016 month=04 day=01
date=20160401
Version=123.456.789 == 123456789
Literal=3.4.5 == 3004005
We have target specific vars
MAN= make.1
save-dollars: 0 =	$
save-dollars: 1 =	$$
save-dollars: 2 =	$$
save-dollars: False =	$
save-dollars: True =	$$
save-dollars: false =	$
save-dollars: true =	$$
save-dollars: Yes =	$$
save-dollars: No =	$
save-dollars: yes =	$$
save-dollars: no =	$
save-dollars: On =	$$
save-dollars: Off =	$
save-dollars: ON =	$$
save-dollars: OFF =	$
save-dollars: on =	$$
save-dollars: off =	$
export-appended: env
export-appended: env
export-appended: env mk
parse-dynamic: parse-dynamic  parse-dynamic  before
parse-dynamic: parse-dynamic  parse-dynamic  after
parse-dynamic: parse-dynamic  parse-dynamic  after
varerror-unclosed:begin
bmake.exe[1]: Unclosed variable ""
ECHO is on.
bmake.exe[1]: Unclosed variable "UNCLOSED"
ECHO is on.
bmake.exe[1]: Unclosed variable "UNCLOSED"
ECHO is on.
bmake.exe[1]: Unclosed variable "PATTERN"
bmake.exe[1]: Unclosed expression, expecting '}' for modifier "M${PATTERN" of variable "UNCLOSED" with value ""
ECHO is on.
bmake.exe[1]: Unclosed variable "param"
bmake.exe[1]: Unclosed variable "UNCLOSED."
ECHO is on.
ECHO is on.
bmake.exe[1]: Unclosed variable "UNCLOSED.1"
ECHO is on.
bmake.exe[1]: Unclosed variable "UNCLOSED.2"
ECHO is on.
bmake.exe[1]: Unclosed variable "UNCLOSED.3"
ECHO is on.
bmake.exe[1]: Unclosed variable "UNCLOSED_ORIG"
ECHO is on.
varerror-unclosed:end
target1-flags: we have: one two 
target2-flags: we have: one two three four
0
